name: Release email-service Image

on:
  push:
    branches:
    - main
    paths:
    - 'images/microservices-orders/email-service/**'
  workflow_dispatch:

jobs:
  build:
    name: Release email-service Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=cnfldemos/email-service
          SHA=$(git log -1 --pretty=%h)
          TAGS="${DOCKER_IMAGE}:sha-${SHA}"
          echo ::set-output name=tags::${TAGS}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: images/microservices-orders/email-service
          file: images/microservices-orders/email-service/Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}

