# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test orders-service

on:
  push:
    # Testing is executed in the release job on push to master
    # branches: [ master ]
    # paths:
    # - 'apps/microservices-orders/orders-service/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'apps/microservices-orders/orders-service/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/microservices-orders/orders-service/

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test
      run: make test
