apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  variant: dev
resources:
- ../base/
patchesStrategicMerge:
- connect/connect-service.yaml
- connect/connect-operator.yaml
- connect/orders-bigquery-sink-config.yaml
- ccloud/microservices-ccloud-environment.yaml
- microservices-orders/orders-service.yaml
